Demo branch
beta-bv/Zuypr pull request #77
Opened 2022-12-13 11:00 UTC by ItsSiem

Enkele dingen professioneler gemaakt

2022-12-13 11:01 UTC, luximus-hunter approved these changes

2022-12-18 20:16 UTC, markvklompenburg requested changes

2022-12-18 20:16 UTC, markvklompenburg commented on Model/dummydb.cs
>                      // User 0 sends a message with the text "uh oh"
Comment tekst aanpassen

2022-12-18 20:16 UTC, markvklompenburg commented on Model/dummydb.cs
>                      // User 1 then responds (as expected) with "stinky"
Comment tekst aanpassen staat nog stinky

2022-12-18 20:16 UTC, markvklompenburg commented on Model/dummydb.cs
>                  // Pick random amount of "uh oh, stinky" pairs between 1 and 15
Comment tekst aanpassen staat nog stinky

2022-12-19 12:02 UTC, luximus-hunter commented
close #74?

2023-01-09 08:22 UTC, closed without merging